server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Postgres@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: aptota.technologies@gmail.com
    password: gowf lptm vtdp qcia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: b3k1pSynBpbxCqP9QyWh7S60XIoxAd7wAdyztlLFbC5cv4Izbp8SY+TikCMmzXpE
  expiration: 86400000  # 24 hours

otp:
  expiration: 300000  # 5 minutes

sms:
  provider:
    api:
      key: 580b577486b7f159be009ae54a2d1354
      url: https://api.twilio.com/2010-04-01/Accounts/AC658d87fc439bf95190995f22d79e37d3/Messages.json

app:
  name: Auth Server
  support:
    email: support@yourapp.com

twilio:
  account-sid: AC658d87fc439bf95190995f22d79e37d3
  auth-token: 580b577486b7f159be009ae54a2d1354
  from-number: +14435683576   # Twilio phone number